use axotyped::{
    AuthScheme, GeneratorConfig, HttpMethod, RouteCollection, RouteDefinition, Visibility,
    api_routes, generate, generate_with_warnings,
};

fn yauth_config() -> GeneratorConfig {
    GeneratorConfig {
        bindings_dir: "./bindings".into(),
        output_path: "./packages/client/src/generated.ts".into(),
        factory_name: "createYAuthClient".into(),
        enable_groups: true,
        error_class_name: "YAuthError".into(),
        options_interface_name: "YAuthClientOptions".into(),
        default_credentials: "include".into(),
        type_import_prefix: "../../../../bindings".into(),
        format_command: None,
        ws_ticket_path: None,
        large_int_type: "number".into(),
        auth_scheme: AuthScheme::Bearer,
        csrf_header_name: None,
    }
}

fn sample_routes() -> axotyped::RouteCollection {
    let mut routes = api_routes! {
        getSession: GET "/session" [auth]
            -> SessionResponse;
        logout: POST "/logout" [auth]
            -> SuccessResponse;
        updateProfile: PATCH "/me" [auth]
            body: UpdateProfileRequest -> ProfileResponse;
    };

    let ep = api_routes! {
        @group emailPassword

        register: POST "/register" [public]
            body: RegisterRequest -> MessageResponse;
        login: POST "/login" [public]
            body: LoginRequest -> LoginResponse;
        verify: POST "/verify-email" [public]
            body: VerifyEmailRequest -> MessageResponse;
        changePassword: POST "/change-password" [auth]
            body: ChangePasswordRequest -> MessageResponse;
    };
    routes.extend(ep);

    let admin = api_routes! {
        @group admin

        listUsers: GET "/admin/users" [auth]
            query: ListUsersQuery -> ListUsersResponse;
        getUser: GET "/admin/users/{id}" [auth]
            -> UserResponse;
        deleteUser: DELETE "/admin/users/{id}" [auth];
        banUser: POST "/admin/users/{id}/ban" [auth]
            body: BanRequest -> UserResponse;
    };
    routes.extend(admin);

    let oauth = api_routes! {
        @group oauth

        authorize: GET "/oauth/{provider}/authorize" [redirect]
            query: AuthorizeQuery;
        callback: POST "/oauth/{provider}/callback" [public]
            body: CallbackBody -> AuthResponse;
    };
    routes.extend(oauth);

    let ws = api_routes! {
        @group realtime

        wsUpgrade: GET "/ws" [ws]
            send: ClientEvent, receive: ServerEvent
            query: WsParams;
    };
    routes.extend(ws);

    routes
}

#[test]
fn generic_types_generate_separate_imports() {
    // ContentResponse<Dialog> should import ContentResponse and Dialog separately,
    // not produce a broken "ContentResponse<Dialog>" import with <> in the path.
    let routes = api_routes! {
        getDialogs: GET "/dialogs"
            -> ContentResponse<Dialog>;
    };
    let config = GeneratorConfig {
        enable_groups: false,
        ..Default::default()
    };
    let output = generate(&routes, &config);

    // Should import each type separately
    assert!(
        output.contains("import type { ContentResponse }"),
        "should import ContentResponse separately, got:\n{}",
        output
    );
    assert!(
        output.contains("import type { Dialog }"),
        "should import Dialog separately, got:\n{}",
        output
    );

    // Should NOT contain angle brackets in import paths
    assert!(
        !output.contains("from \"./ContentResponse<Dialog>\""),
        "import path should not contain angle brackets, got:\n{}",
        output
    );
    assert!(
        !output.contains("import type { ContentResponse<Dialog> }"),
        "import should not contain angle brackets in the type name, got:\n{}",
        output
    );
}

#[test]
fn generates_valid_output() {
    let routes = sample_routes();
    let config = yauth_config();
    let output = generate(&routes, &config);

    // Header
    assert!(output.starts_with("// Auto-generated by axotyped. Do not edit.\n"));

    // Imports exist for custom types
    assert!(output.contains("import type { RegisterRequest }"));
    assert!(output.contains("import type { LoginResponse }"));
    assert!(output.contains("import type { ListUsersQuery }"));
    assert!(output.contains("import type { UserResponse }"));
    assert!(output.contains("import type { AuthorizeQuery }"));

    // Error class
    assert!(output.contains("export class YAuthError extends Error"));

    // Options interface
    assert!(output.contains("export interface YAuthClientOptions"));

    // Factory function
    assert!(
        output.contains(
            "export function createYAuthClient(options: YAuthClientOptions): YAuthClient"
        )
    );

    // Type export
    assert!(
        output.contains("export type YAuthClient = ReturnType<typeof createYAuthClientRoutes> & {")
    );
}

#[test]
fn generates_ungrouped_routes() {
    let routes = sample_routes();
    let config = yauth_config();
    let output = generate(&routes, &config);

    // Top-level routes — fully generator-controlled options, method always enforced
    assert!(output.contains("getSession: () => request<SessionResponse>(\"/session\", { method: \"GET\", auth: true, permissive: false, allowRedirects: false })"));
    assert!(output.contains("logout: () => request<SuccessResponse>(\"/logout\", { method: \"POST\", auth: true, permissive: false, allowRedirects: false })"));
}

#[test]
fn generates_grouped_routes() {
    let routes = sample_routes();
    let config = yauth_config();
    let output = generate(&routes, &config);

    // Group structure (keys are quoted+escaped property names)
    assert!(output.contains("\"emailPassword\": {"));
    assert!(output.contains("\"admin\": {"));
    assert!(output.contains("\"oauth\": {"));

    // Group methods take only their declared params
    assert!(output.contains("register: (body: RegisterRequest)"));
    assert!(output.contains("login: (body: LoginRequest)"));
}

#[test]
fn generates_path_params() {
    let routes = sample_routes();
    let config = yauth_config();
    let output = generate(&routes, &config);

    // Path params become function args and encoded template literals
    assert!(output.contains("getUser: (id: string)"));
    assert!(output.contains("`/admin/users/${encodeURIComponent(id)}`"));
    assert!(output.contains("banUser: (id: string, body: BanRequest)"));
    // Options pinned by the generator, no caller spread
    assert!(output.contains("{ method: \"GET\", auth: true, permissive: false, allowRedirects: false }"));
}

#[test]
fn generates_query_params() {
    let routes = sample_routes();
    let config = yauth_config();
    let output = generate(&routes, &config);

    // Query params only
    assert!(output.contains("listUsers: (query?: ListUsersQuery)"));
    assert!(output.contains("query"));
}

#[test]
fn generates_redirect_routes() {
    let routes = sample_routes();
    let config = yauth_config();
    let output = generate(&routes, &config);

    // Redirect routes generate URL builders, not fetch calls
    assert!(output.contains("authorize:"));
    assert!(output.contains("options.baseUrl"));
    // Should NOT contain request<...> for redirect routes
    let authorize_section = output
        .split("authorize:")
        .nth(1)
        .unwrap()
        .split('}')
        .next()
        .unwrap();
    assert!(!authorize_section.contains("request<"));
}

#[test]
fn generates_auth_flag() {
    let routes = sample_routes();
    let config = yauth_config();
    let output = generate(&routes, &config);

    // Auth routes have auth: true in options
    assert!(output.contains("auth: true"));
}

#[test]
fn generates_void_return_for_no_response() {
    let routes = sample_routes();
    let config = yauth_config();
    let output = generate(&routes, &config);

    // deleteUser has no response type (8 spaces indent: 6 base + 2 continuation)
    assert!(output.contains("deleteUser: (id: string) =>\n        request<void>"));
}

#[test]
fn generates_request_helper() {
    let routes = sample_routes();
    let config = yauth_config();
    let output = generate(&routes, &config);

    // Request helper should contain error handling
    assert!(output.contains("function createRequest(options: YAuthClientOptions)"));
    assert!(output.contains("new YAuthError("));
    assert!(output.contains("credentials"));
    assert!(output.contains("getToken"));
}

#[test]
fn redirect_defaults_to_error_with_server_side_opt_in() {
    let routes = sample_routes();
    let output = generate(&routes, &yauth_config());

    // Sane default: refuse redirects so 3xx can't bounce creds elsewhere.
    // Only credentialless calls to routes declaring `[allow_redirects]` follow.
    assert!(output.contains("const canFollowRedirects ="));
    assert!(output.contains("!auth && credentials === \"omit\" && opts.allowRedirects === true"));
    assert!(output.contains("redirect: canFollowRedirects ? \"follow\" : \"error\""));
    // Default routes pin the flag off.
    assert!(output.contains("allowRedirects: false"));
    // Authenticated requests also bypass browser cache; auth defaults false.
    assert!(output.contains("cache: \"no-store\""));
    assert!(output.contains("auth = false"));
    // Cookies count as credentials, not just auth:true.
    assert!(output.contains("credentials !== \"omit\""));
}

#[test]
fn allow_redirects_flag_is_server_declared() {
    let routes = api_routes! {
        hook: POST "/hook" [public, allow_redirects] body: HookBody -> SuccessResponse;
        plain: GET "/plain" [public];
    };
    assert!(routes.routes()[0].allow_redirects, "flag must set the route property");
    assert!(!routes.routes()[1].allow_redirects, "default must refuse");

    let output = generate(&routes, &yauth_config());
    let lines: Vec<&str> = output.lines().collect();
    let hook_idx = lines
        .iter()
        .position(|l| l.contains("hook:"))
        .expect("hook method should be emitted");
    let hook_call = format!("{}\n{}", lines[hook_idx], lines[hook_idx + 1]);
    assert!(
        hook_call.contains("allowRedirects: true"),
        "declared route must bake follow in: {hook_call:?}"
    );
    let plain_line = output
        .lines()
        .find(|l| l.contains("plain:"))
        .expect("plain method should be emitted");
    assert!(
        plain_line.contains("allowRedirects: false"),
        "default route must refuse: {plain_line:?}"
    );
}

#[test]
fn public_cookie_route_with_insecure_http_requires_omit() {
    use axotyped::{AuthScheme, api_routes};
    let routes = api_routes! {
        health: GET "/health" [public];
    };
    let mut config = yauth_config();
    config.auth_scheme = AuthScheme::Cookie;
    let output = generate(&routes, &config);
    // Guard must see the effective credential mode, not just auth.
    assert!(output.contains("assertSecureTransport(url, { allowInsecureHttp: options.allowInsecureHttp === true, auth, credentials })"));
}

#[test]
fn route_options_carry_no_caller_spread() {
    let routes = sample_routes();
    let output = generate(&routes, &yauth_config());

    // Route calls are fully generator-controlled: no `...opts` spread, so
    // neither `permissive` nor `allowRedirects` is runtime-flippable…
    for line in output.lines().filter(|l| l.contains("request<")) {
        assert!(
            !line.contains("...opts"),
            "route call must not spread caller opts: {line:?}"
        );
    }
    // …route methods take no options argument at all (helper overloads
    // excluded: only `=>` route definitions are caller-reachable)…
    for line in output
        .lines()
        .filter(|l| l.contains("request<") && l.contains("=>"))
    {
        assert!(
            !line.contains("opts?:"),
            "route method must not accept caller opts: {line:?}"
        );
    }
    // …and the single option type documents the fields as generator-pinned.
    assert!(
        output.contains("never user-supplied"),
        "option type must document generator pinning"
    );
    assert!(
        !output.contains("InternalRequestOptions"),
        "no split internal type should remain"
    );
}

#[test]
fn permissive_flag_marks_route_best_effort_but_credentialed() {
    let routes = api_routes! {
        feed: GET "/feed" [permissive] -> FeedResponse;
        open: GET "/health" [public];
    };
    let feed = &routes.routes()[0];
    assert_eq!(feed.visibility, Visibility::Permissive);
    assert_eq!(feed.declared, Visibility::Permissive);
    assert!(feed.is_credentialed(), "permissive stays credentialed for guard/cache");

    let output = generate(&routes, &yauth_config());
    // Per-route opts carry both flags; auth keeps guard/cache/redirect treatment.
    assert!(output.contains("permissive: true"));
    assert!(output.contains("feed: () =>"));
    // Bearer best-effort branch attaches when available, never throws.
    assert!(output.contains("if (permissive)"));
    // Public routes carry no auth flag but still pin permissive:false.
    let open_line = output
        .lines()
        .find(|l| l.contains("open:"))
        .expect("open method should be emitted");
    assert!(
        !open_line.contains("auth: true") && open_line.contains("permissive: false"),
        "public route must pin permissive:false without auth: {open_line:?}"
    );
}

#[test]
fn permissive_cookie_route_skips_omit_refusal() {
    let routes = api_routes! {
        feed: GET "/feed" [permissive] -> FeedResponse;
    };
    let mut config = yauth_config();
    config.auth_scheme = AuthScheme::Cookie;
    let output = generate(&routes, &config);
    // Anonymous (`omit`) is a valid outcome for permissive: the refusal is
    // gated on `!permissive`.
    assert!(
        output.contains("if (auth && !permissive"),
        "omit refusal must skip permissive routes, got:\n{}",
        output
    );
}

#[test]
fn permissive_route_produces_no_warnings() {
    let routes = api_routes! {
        feed: GET "/feed" [permissive] -> FeedResponse;
    };
    // Under None the route degrades to anonymous — functional, nothing to report.
    let mut none = yauth_config();
    none.auth_scheme = AuthScheme::None;
    let (_, warnings) = generate_with_warnings(&routes, &none);
    assert!(warnings.is_empty(), "permissive must not warn: {warnings:?}");
}

#[test]
fn flat_mode_no_groups() {
    let routes = sample_routes();
    let config = GeneratorConfig {
        enable_groups: false,
        ..yauth_config()
    };
    let output = generate(&routes, &config);

    // Should not have group objects
    assert!(!output.contains("emailPassword: {"));
    assert!(!output.contains("admin: {"));
    // All routes at top level
    assert!(output.contains("register:"));
    assert!(output.contains("listUsers:"));
}

#[test]
fn check_detects_out_of_sync() {
    use std::io::Write;

    let routes = sample_routes();
    let dir = std::env::temp_dir().join("axotyped_test");
    std::fs::create_dir_all(&dir).unwrap();
    let output_path = dir.join("generated.ts");

    let config = GeneratorConfig {
        output_path: output_path.to_string_lossy().into(),
        ..yauth_config()
    };

    // Write wrong content
    let mut f = std::fs::File::create(&output_path).unwrap();
    writeln!(f, "// old content").unwrap();
    drop(f);

    // Check should fail
    let result = axotyped::check(&routes, &config);
    assert!(result.is_err());

    // Now write correct content
    axotyped::generate_to_file(&routes, &config).unwrap();

    // Check should pass
    let result = axotyped::check(&routes, &config);
    assert!(result.is_ok());

    // Cleanup
    std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn snapshot_yauth_style_output() {
    let routes = sample_routes();
    let config = yauth_config();
    let output = generate(&routes, &config);

    // Write snapshot for manual inspection
    let snapshot_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/snapshots/yauth_style.ts"
    );
    std::fs::write(snapshot_path, &output).unwrap();

    // Verify it can be re-read and matches
    let re_read = std::fs::read_to_string(snapshot_path).unwrap();
    assert_eq!(output, re_read);
}

#[test]
fn generate_to_file_runs_format_command() {
    let routes = sample_routes();
    let dir = std::env::temp_dir().join("axotyped_fmt_test");
    std::fs::create_dir_all(&dir).unwrap();
    let output_path = dir.join("generated.ts");

    // Use sed to replace a known string, proving the formatter ran
    let config = GeneratorConfig {
        output_path: output_path.to_string_lossy().into(),
        format_command: Some("sed -i s/Auto-generated/FORMATTED/".into()),
        ..yauth_config()
    };

    axotyped::generate_to_file(&routes, &config).unwrap();

    let content = std::fs::read_to_string(&output_path).unwrap();
    assert!(
        content.contains("FORMATTED"),
        "format command should have replaced 'Auto-generated' with 'FORMATTED'"
    );
    assert!(
        !content.contains("Auto-generated"),
        "original text should have been replaced"
    );

    std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn check_passes_with_format_command() {
    let routes = sample_routes();
    let dir = std::env::temp_dir().join("axotyped_fmt_check");
    std::fs::create_dir_all(&dir).unwrap();
    let output_path = dir.join("generated.ts");

    let config = GeneratorConfig {
        output_path: output_path.to_string_lossy().into(),
        format_command: Some("sed -i s/Auto-generated/FORMATTED/".into()),
        ..yauth_config()
    };

    // generate_to_file writes + formats
    axotyped::generate_to_file(&routes, &config).unwrap();

    // check should pass (generates to temp, formats, compares)
    let result = axotyped::check(&routes, &config);
    assert!(
        result.is_ok(),
        "check should pass after generate_to_file with same format_command"
    );

    std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn check_fails_when_format_command_not_applied() {
    let routes = sample_routes();
    let dir = std::env::temp_dir().join("axotyped_fmt_mismatch");
    std::fs::create_dir_all(&dir).unwrap();
    let output_path = dir.join("generated.ts");

    // Write unformatted output
    let unformatted_config = GeneratorConfig {
        output_path: output_path.to_string_lossy().into(),
        format_command: None,
        ..yauth_config()
    };
    axotyped::generate_to_file(&routes, &unformatted_config).unwrap();

    // Check with a format_command — the on-disk file is unformatted, so it should fail
    let formatted_config = GeneratorConfig {
        output_path: output_path.to_string_lossy().into(),
        format_command: Some("sed -i s/Auto-generated/FORMATTED/".into()),
        ..yauth_config()
    };
    let result = axotyped::check(&routes, &formatted_config);
    assert!(
        result.is_err(),
        "check should fail when on-disk file was not formatted"
    );

    std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn format_command_none_preserves_existing_behavior() {
    let routes = sample_routes();
    let dir = std::env::temp_dir().join("axotyped_no_fmt");
    std::fs::create_dir_all(&dir).unwrap();
    let output_path = dir.join("generated.ts");

    let config = GeneratorConfig {
        output_path: output_path.to_string_lossy().into(),
        format_command: None,
        ..yauth_config()
    };

    axotyped::generate_to_file(&routes, &config).unwrap();

    // Content should match raw generate() output exactly
    let content = std::fs::read_to_string(&output_path).unwrap();
    let expected = generate(&routes, &config);
    assert_eq!(content, expected);

    // check should pass
    let result = axotyped::check(&routes, &config);
    assert!(result.is_ok());

    std::fs::remove_dir_all(&dir).ok();
}

// ---------------------------------------------------------------------------
// WebSocket generation
// ---------------------------------------------------------------------------

#[test]
fn generates_websocket_route() {
    let routes = sample_routes();
    let config = yauth_config();
    let output = generate(&routes, &config);

    // Should have the realtime group (quoted+escaped key)
    assert!(output.contains("\"realtime\": {"));

    // Should have TypedWebSocket interface and helper
    assert!(output.contains("export interface TypedWebSocket<TSend, TReceive>"));
    assert!(output.contains("function createTypedWebSocket<TSend, TReceive>"));

    // Should convert http to ws
    assert!(output.contains("options.baseUrl.replace(/^http/"));

    // Should NOT use request<...> for WS routes
    let ws_section = output
        .split("wsUpgrade:")
        .nth(1)
        .unwrap()
        .split('}')
        .next()
        .unwrap();
    assert!(!ws_section.contains("request<"));
}

#[test]
fn generates_websocket_with_query() {
    let routes = sample_routes();
    let config = yauth_config();
    let output = generate(&routes, &config);

    // Should have query param handling for WS
    assert!(output.contains("WsParams"));

    // The WS method should accept query param
    assert!(output.contains("wsUpgrade: (query?: WsParams)"));

    // Should have typed return with ClientEvent and ServerEvent
    assert!(output.contains("TypedWebSocket<ClientEvent, ServerEvent>"));
}

#[test]
fn generates_websocket_no_query() {
    let routes = api_routes! {
        wsConnect: GET "/ws" [ws]
            send: ClientEvent, receive: ServerEvent;
    };
    let config = yauth_config();
    let output = generate(&routes, &config);

    // Should still generate typed WS
    assert!(output.contains("TypedWebSocket<ClientEvent, ServerEvent>"));

    // No query param handling in the WS method itself
    let ws_section = output
        .split("wsConnect:")
        .nth(1)
        .unwrap()
        .split('}')
        .next()
        .unwrap();
    assert!(!ws_section.contains("URLSearchParams"));
}

#[test]
fn generates_websocket_with_path_params() {
    let routes = api_routes! {
        sessionWs: GET "/ws/{sessionId}" [ws]
            send: ClientEvent, receive: ServerEvent
            query: WsParams;
    };
    let config = yauth_config();
    let output = generate(&routes, &config);

    // Should have path param as function arg
    assert!(output.contains("sessionWs: (sessionId: string, query?: WsParams)"));

    // Should use encoded template literal for path
    assert!(output.contains("${encodeURIComponent(sessionId)}"));

    // Should return typed WS
    assert!(output.contains("TypedWebSocket<ClientEvent, ServerEvent>"));
}

#[test]
fn generates_websocket_imports_event_types() {
    let routes = api_routes! {
        wsUpgrade: GET "/ws" [ws]
            send: ClientEvent, receive: ServerEvent
            query: WsParams;
    };
    let config = yauth_config();
    let output = generate(&routes, &config);

    // Should import the event types
    assert!(output.contains("import type { ClientEvent }"));
    assert!(output.contains("import type { ServerEvent }"));
    assert!(output.contains("import type { WsParams }"));
}

#[test]
fn generates_websocket_typed_send_and_receive() {
    let routes = api_routes! {
        wsUpgrade: GET "/ws" [ws]
            send: ClientEvent, receive: ServerEvent;
    };
    let config = yauth_config();
    let output = generate(&routes, &config);

    // TypedWebSocket interface should have send and onMessage
    assert!(output.contains("send(event: TSend): void"));
    assert!(output.contains("onMessage(handler: (event: TReceive) => void): void"));

    // createTypedWebSocket should use JSON.stringify/parse
    assert!(output.contains("JSON.stringify(event)"));
    assert!(output.contains("JSON.parse(raw.data"));
}

// ===========================================================================
// Auth scheme dimension (bearer | cookie | none)
// ===========================================================================

#[test]
fn default_config_is_bearer_fail_closed_with_same_origin_credentials() {
    let routes = api_routes! {
        getSession: GET "/session" [auth] -> SessionResponse;
    };
    let output = generate(&routes, &GeneratorConfig::default());

    assert!(output.contains("getToken?: () => Promise<string | null>"));
    assert!(output.contains("headers.Authorization = `Bearer ${token}`"));
    // Cookies no longer leak cross-origin by default; token clients don't need them.
    assert!(output.contains("credentials = \"same-origin\""));
}

#[test]
fn cookie_scheme_swaps_get_token_for_csrf_and_refuses_omitted_credentials() {
    let routes = api_routes! {
        getSession: GET "/session" [auth] -> SessionResponse;
        updateProfile: PATCH "/me" [auth] body: UpdateProfileRequest -> ProfileResponse;
    };
    let mut config = yauth_config();
    config.auth_scheme = AuthScheme::Cookie;
    config.csrf_header_name = Some("X-CSRF-Token".into());
    let output = generate(&routes, &config);

    // No Bearer machinery anywhere.
    assert!(
        !output.contains("getToken"),
        "cookie client must not emit getToken"
    );
    assert!(
        !output.contains("Authorization"),
        "cookie client must not emit Authorization headers"
    );

    // Typed CSRF option + header attach on mutating requests.
    assert!(output.contains("csrfToken?: () => Promise<string | null> | string | null"));
    assert!(output.contains("headers[\"X-CSRF-Token\"] = csrfToken"));

    // Fail-closed analog: stripping cookies from an auth route aborts the call.
    assert!(
        output.contains(
            "options.credentials is \"omit\"; refusing to send an unauthenticated request"
        )
    );
}

#[test]
fn cookie_scheme_without_csrf_config_emits_no_plumbing() {
    let routes = api_routes! {
        updateProfile: PATCH "/me" [auth] body: UpdateProfileRequest -> ProfileResponse;
    };
    let mut config = yauth_config();
    config.auth_scheme = AuthScheme::Cookie;
    let output = generate(&routes, &config);

    assert!(output.contains("options.credentials is \"omit\""));
    assert!(!output.contains("csrfToken"));
    assert!(!output.contains("X-CSRF-Token"));
}

#[test]
fn cookie_ws_auth_rides_cookies_without_ticket_handshake() {
    let routes = api_routes! {
        wsUpgrade: GET "/ws" [ws, auth]
            send: ClientEvent, receive: ServerEvent;
    };
    let mut config = yauth_config();
    config.auth_scheme = AuthScheme::Cookie;
    let (output, warnings) = generate_with_warnings(&routes, &config);

    // No diagnostic: session cookies ride same-origin WS upgrades natively.
    assert!(
        warnings.is_empty(),
        "cookie scheme has a native WS credential pathway: {warnings:?}"
    );
    assert!(
        !output.contains("__wsTicket"),
        "cookie WS must not use ticket handshake"
    );
    // Fail closed: omit would silently send the upgrade unauthenticated
    // (WS has no credentials option), so the client must refuse it.
    assert!(
        output.contains("options.credentials ??") && output.contains("refusing to send an unauthenticated upgrade"),
        "cookie [ws][auth] must reject credentials omit before new WebSocket"
    );
}

#[test]
fn none_scheme_generates_no_auth_machinery_and_warns_on_auth_routes() {
    let routes = api_routes! {
        getSession: GET "/session" [auth] -> SessionResponse;
        health: GET "/health" [public] -> SuccessResponse;
    };
    let mut config = yauth_config();
    config.auth_scheme = AuthScheme::None;
    let (output, warnings) = generate_with_warnings(&routes, &config);

    assert!(
        !output.contains("getToken"),
        "none client must not emit getToken"
    );
    assert!(
        warnings.iter().any(|w| w.contains("getSession")),
        "authenticated route under scheme none must warn, got {warnings:?}"
    );
    assert!(
        !warnings.iter().any(|w| w.contains("health")),
        "public routes must not warn under scheme none"
    );
}

// ===========================================================================
// Server-derived auth metadata (declared-public contradiction)
// ===========================================================================

fn manual_route(
    name: &str,
    path: &str,
    visibility: axotyped::Visibility,
    declared: axotyped::Visibility,
) -> RouteDefinition {
    RouteDefinition {
        name: name.into(),
        method: HttpMethod::Get,
        path: path.into(),
        visibility,
        declared,
        body_type: None,
        response_type: None,
        query_type: None,
        path_params: axotyped::extract_path_params(path),
        group: None,
        allow_redirects: false,
        redirect: false,
        websocket: false,
        ws_send_type: None,
        ws_receive_type: None,
    }
}

#[test]
fn public_declared_but_protected_route_produces_contradiction_warning() {
    let mut routes = RouteCollection::new();
    routes.push(manual_route(
        "hook",
        "/webhooks/hook",
        axotyped::Visibility::Private,
        axotyped::Visibility::Public,
    ));
    routes.push(manual_route(
        "admin",
        "/admin/users",
        axotyped::Visibility::Private,
        axotyped::Visibility::Private,
    ));

    let (_, warnings) = generate_with_warnings(&routes, &yauth_config());

    assert!(
        warnings
            .iter()
            .any(|w| w.contains("hook") && w.contains("auth layer")),
        "contradiction between public declaration and protection must warn, got {warnings:?}"
    );
    assert!(
        !warnings.iter().any(|w| w.contains("admin")),
        "protected-without-declaration is the expected steady state"
    );
}

#[test]
fn consistently_public_or_protected_routes_never_warn_about_layering() {
    let mut routes = RouteCollection::new();
    routes.push(manual_route(
        "open",
        "/health",
        axotyped::Visibility::Public,
        axotyped::Visibility::Public,
    ));
    routes.push(manual_route(
        "gated",
        "/me",
        axotyped::Visibility::Private,
        axotyped::Visibility::Private,
    ));

    let (_, warnings) = generate_with_warnings(&routes, &yauth_config());
    assert!(
        warnings.is_empty(),
        "consistent declarations produce no diagnostics: {warnings:?}"
    );
}
