// Auto-generated by axotyped. Do not edit.

import type { AuthResponse } from "../../../../bindings/AuthResponse";
import type { AuthorizeQuery } from "../../../../bindings/AuthorizeQuery";
import type { BanRequest } from "../../../../bindings/BanRequest";
import type { CallbackBody } from "../../../../bindings/CallbackBody";
import type { ChangePasswordRequest } from "../../../../bindings/ChangePasswordRequest";
import type { ClientEvent } from "../../../../bindings/ClientEvent";
import type { ListUsersQuery } from "../../../../bindings/ListUsersQuery";
import type { ListUsersResponse } from "../../../../bindings/ListUsersResponse";
import type { LoginRequest } from "../../../../bindings/LoginRequest";
import type { LoginResponse } from "../../../../bindings/LoginResponse";
import type { MessageResponse } from "../../../../bindings/MessageResponse";
import type { ProfileResponse } from "../../../../bindings/ProfileResponse";
import type { RegisterRequest } from "../../../../bindings/RegisterRequest";
import type { ServerEvent } from "../../../../bindings/ServerEvent";
import type { SessionResponse } from "../../../../bindings/SessionResponse";
import type { SuccessResponse } from "../../../../bindings/SuccessResponse";
import type { UpdateProfileRequest } from "../../../../bindings/UpdateProfileRequest";
import type { UserResponse } from "../../../../bindings/UserResponse";
import type { VerifyEmailRequest } from "../../../../bindings/VerifyEmailRequest";
import type { WsParams } from "../../../../bindings/WsParams";

export type * from "../../../../bindings";
export class YAuthError extends Error {
  constructor(message: string, public status: number, public body?: unknown) {
    super(message);
    this.name = "YAuthError";
  }
}

export interface YAuthClientOptions {
  baseUrl: string;
  getToken?: () => Promise<string | null>;
  credentials?: RequestCredentials;
  fetch?: typeof fetch;
  onError?: (error: YAuthError) => void;
  /**
   * Opt-in ONLY for development against a non-loopback http:// target
   * (e.g. an Expo device hitting your LAN IP). Loopback hosts
   * (localhost / 127.0.0.1 / ::1 / *.localhost) are always permitted over
   * http without this flag. Never set in production — CI should assert its
   * absence.
   */
  allowInsecureHttp?: boolean;
}

type RequestOptions = {
  method?: string;
  body?: unknown;
  query?: Record<string, unknown>;
  auth?: boolean;
};

function assertSecureTransport(
  url: string,
  allowInsecureHttp: boolean,
): void {
  // Transport guard: credentials must only ride https. Loopback hosts are
  // inherently local and always allowed over http; anything else requires
  // the explicit allowInsecureHttp development opt-in. Fails closed on
  // unparseable URLs and non-http(s) protocols.
  let parsed: URL;
  try {
    parsed = new URL(url);
  } catch {
    throw new Error(
      `Client produced an unparseable URL (${JSON.stringify(url)}); refusing to send credentials.`,
    );
  }
  if (parsed.protocol === "https:") return;
  const h = parsed.hostname;
  const isLoopback =
    h === "localhost" ||
    h.endsWith(".localhost") ||
    h === "127.0.0.1" ||
    h === "::1" ||
    h === "[::1]";
  const insecureAllowed =
    parsed.protocol === "http:" && (isLoopback || allowInsecureHttp);
  if (!insecureAllowed) {
    throw new Error(
      parsed.protocol === "http:"
        ? `Refusing to send credentials over http:// to non-loopback host "${h}". Use https:// in production; set allowInsecureHttp on the client options for LAN/device development.`
        : `Unsupported protocol ${parsed.protocol} for credential-bearing requests.`,
    );
  }
}

function createRequest(options: YAuthClientOptions) {
  const { baseUrl, credentials = "include" } = options;
  async function request<T>(
    path: string,
    opts: RequestOptions = {},
  ): Promise<T> {
    const { method = "GET", body, query, auth } = opts;
    // Resolve fetch at call time (not at client creation) so OTel
    // instrumentation patches are picked up even when the client
    // module is imported before telemetry initializes.
    const fetchFn = options.fetch ?? globalThis.fetch;

    let url = `${baseUrl}${path}`;
    if (query) {
      const params = new URLSearchParams();
      for (const [key, value] of Object.entries(query)) {
        if (value !== undefined && value !== null) {
          params.set(key, String(value));
        }
      }
      const qs = params.toString();
      if (qs) url += `?${qs}`;
    }

    const headers: Record<string, string> = { "Content-Type": "application/json" };

    // Credentials are only sent over https, to loopback hosts over http,
    // or when the client was explicitly configured with allowInsecureHttp.
    assertSecureTransport(url, options.allowInsecureHttp === true);

    // An [auth] route requires a token: without one configured or returned,
    // the request is aborted rather than sent unauthenticated.
    if (auth) {
      if (!options.getToken) {
        throw new Error(
          `Route declared [auth] but options.getToken was not configured (${method} ${path})`,
        );
      }
      const token = await options.getToken();
      if (!token) {
        throw new Error(
          `options.getToken() returned no token for an [auth] route (${method} ${path})`,
        );
      }
      headers.Authorization = `Bearer ${token}`;
    }

    const response = await fetchFn(url, {
      method,
      credentials,
      headers,
      body: body !== undefined ? JSON.stringify(body) : undefined,
    });

    if (!response.ok) {
      const text = await response.text();
      let message: string;
      let errorBody: unknown;
      try {
        const json = JSON.parse(text);
        message = json.error ?? json.message ?? text;
        errorBody = json;
      } catch {
        message = text;
      }
      const error = new YAuthError(message, response.status, errorBody);
      if (options.onError) options.onError(error);
      throw error;
    }

    const text = await response.text();
    return (text ? JSON.parse(text) : undefined) as T;
  }

  return request;
}

export interface TypedWebSocket<TSend, TReceive> {
  send(event: TSend): void;
  onOpen(handler: () => void): void;
  onMessage(handler: (event: TReceive) => void): void;
  onError(handler: (event: Event) => void): void;
  onClose(handler: (event: CloseEvent) => void): void;
  close(code?: number, reason?: string): void;
  readonly readyState: number;
}

function createTypedWebSocket<TSend, TReceive>(ws: WebSocket): TypedWebSocket<TSend, TReceive> {
  return {
    send(event: TSend) { ws.send(JSON.stringify(event)); },
    onOpen(handler: () => void) { ws.addEventListener("open", handler); },
    onMessage(handler: (event: TReceive) => void) {
      ws.addEventListener("message", (raw: MessageEvent) => {
        handler(JSON.parse(raw.data as string) as TReceive);
      });
    },
    onError(handler: (event: Event) => void) { ws.addEventListener("error", handler); },
    onClose(handler: (event: CloseEvent) => void) { ws.addEventListener("close", handler); },
    close(code?: number, reason?: string) { ws.close(code, reason); },
    get readyState() { return ws.readyState; },
  };
}

export function createYAuthClient(options: YAuthClientOptions) {
  const request = createRequest(options);

  return {
    getSession: () => request<SessionResponse>("/session", { auth: true }),
    logout: () => request<SuccessResponse>("/logout", { method: "POST", auth: true }),
    updateProfile: (body: UpdateProfileRequest) =>
      request<ProfileResponse>("/me", { method: "PATCH", auth: true, body }),

    "admin": {
      listUsers: (query?: ListUsersQuery) =>
        request<ListUsersResponse>("/admin/users", { auth: true, query }),
      getUser: (id: string) =>
        request<UserResponse>(`/admin/users/${encodeURIComponent(id)}`, { auth: true }),
      deleteUser: (id: string) =>
        request<void>(`/admin/users/${encodeURIComponent(id)}`, { method: "DELETE", auth: true }),
      banUser: (id: string, body: BanRequest) =>
        request<UserResponse>(`/admin/users/${encodeURIComponent(id)}/ban`, { method: "POST", auth: true, body }),
    },

    "emailPassword": {
      register: (body: RegisterRequest) =>
        request<MessageResponse>("/register", { method: "POST", auth: true, body }),
      login: (body: LoginRequest) =>
        request<LoginResponse>("/login", { method: "POST", auth: true, body }),
      verify: (body: VerifyEmailRequest) =>
        request<MessageResponse>("/verify-email", { method: "POST", auth: true, body }),
      changePassword: (body: ChangePasswordRequest) =>
        request<MessageResponse>("/change-password", { method: "POST", auth: true, body }),
    },

    "oauth": {
      authorize: (provider: string, query?: AuthorizeQuery) => {
        let url = `${options.baseUrl}/oauth/${encodeURIComponent(provider)}/authorize`;
        if (query) {
          const params = new URLSearchParams();
          for (const [key, value] of Object.entries(query)) {
            if (value !== undefined && value !== null) params.set(key, String(value));
          }
          const qs = params.toString();
          if (qs) url += `?${qs}`;
        }
        return url;
      },
      callback: (provider: string, body: CallbackBody) =>
        request<AuthResponse>(`/oauth/${encodeURIComponent(provider)}/callback`, { method: "POST", auth: true, body }),
    },

    "realtime": {
      wsUpgrade: (query?: WsParams): TypedWebSocket<ClientEvent, ServerEvent> => {
        const baseUrl = options.baseUrl.replace(/^http/, (m) => m === "https" ? "wss" : "ws");
        let url = `${baseUrl}/ws`;
        if (query) {
          const params = new URLSearchParams();
          for (const [key, value] of Object.entries(query)) {
            if (value !== undefined && value !== null) params.set(key, String(value));
          }
          const qs = params.toString();
          if (qs) url += `?${qs}`;
        }
        assertSecureTransport(url, options.allowInsecureHttp === true);
        const ws = new WebSocket(url);
        return createTypedWebSocket<ClientEvent, ServerEvent>(ws);
      },
    },
  };
}

export type YAuthClient = ReturnType<typeof createYAuthClient>;
