// Auto-generated by axotyped. Do not edit.

import type { AuthResponse } from "../../../../bindings/AuthResponse";
import type { AuthorizeQuery } from "../../../../bindings/AuthorizeQuery";
import type { BanRequest } from "../../../../bindings/BanRequest";
import type { CallbackBody } from "../../../../bindings/CallbackBody";
import type { ChangePasswordRequest } from "../../../../bindings/ChangePasswordRequest";
import type { ClientEvent } from "../../../../bindings/ClientEvent";
import type { ListUsersQuery } from "../../../../bindings/ListUsersQuery";
import type { ListUsersResponse } from "../../../../bindings/ListUsersResponse";
import type { LoginRequest } from "../../../../bindings/LoginRequest";
import type { LoginResponse } from "../../../../bindings/LoginResponse";
import type { MessageResponse } from "../../../../bindings/MessageResponse";
import type { ProfileResponse } from "../../../../bindings/ProfileResponse";
import type { RegisterRequest } from "../../../../bindings/RegisterRequest";
import type { ServerEvent } from "../../../../bindings/ServerEvent";
import type { SessionResponse } from "../../../../bindings/SessionResponse";
import type { SuccessResponse } from "../../../../bindings/SuccessResponse";
import type { UpdateProfileRequest } from "../../../../bindings/UpdateProfileRequest";
import type { UserResponse } from "../../../../bindings/UserResponse";
import type { VerifyEmailRequest } from "../../../../bindings/VerifyEmailRequest";
import type { WsParams } from "../../../../bindings/WsParams";

export type * from "../../../../bindings";
export class YAuthError extends Error {
  constructor(message: string, public status: number, public body?: unknown) {
    super(message);

    // Keep native Error behavior when transpiled to older targets:
    // name non-enumerable, prototype chain intact, stack trace captured.
    Object.defineProperty(this, "name", {
      value: "YAuthError",
      enumerable: false,
      configurable: true,
    });
    if (Object.setPrototypeOf !== undefined) {
      Object.setPrototypeOf(this, YAuthError.prototype);
    }
    if ((Error as any).captureStackTrace !== undefined) {
      (Error as any).captureStackTrace(this, this.constructor);
    }
  }
}

export interface YAuthClientOptions {
  baseUrl: string;
  getToken?: () => Promise<string | null>;
  credentials?: RequestCredentials;
  fetch?: typeof fetch;
  onError?: (error: YAuthError) => void;
  /**
   * Default RequestInit merged into every request. Useful for AbortSignals
   * (cancellation/timeouts), cache policy, keepalive, and priority hints.
   * Per-request values passed through a route's options take precedence.
   */
  requestInit?: Omit<RequestInit, "headers" | "method" | "body"> & {
    headers?: Record<string, string>;
  };
  /**
   * Opt-in ONLY for development against a non-loopback http:// target
   * (e.g. an Expo device hitting your LAN IP). Loopback hosts
   * (localhost / 127.0.0.1 / ::1 / *.localhost) are always permitted over
   * http without this flag. Never set in production — CI should assert its
   * absence.
   */
  allowInsecureHttp?: boolean;
}

/** Route call options. Fully generator-pinned per route — route methods take
    no caller options, so these fields are never user-supplied. */
type RequestOptions = {
  method?: string;
  body?: unknown;
  query?: Record<string, unknown>;
  auth?: boolean;
  /** Attach credentials when available, never require them. */
  permissive?: boolean;
  /** Follow redirects only for credentialless calls to declaring routes. */
  allowRedirects?: boolean;
};
/** The `request` helper produced by `createRequest`, for the routes factory. */
type RequestFn = <T>(path: string, opts?: RequestOptions) => Promise<T>;

function assertSecureTransport(
  url: string,
  opts: { allowInsecureHttp: boolean; auth: boolean; credentials: string },
): void {
  const { allowInsecureHttp, auth, credentials } = opts;
  // Transport guard: credentials must only ride https. Loopback hosts are
  // inherently local and always allowed over http; anything else requires
  // the explicit allowInsecureHttp development opt-in. Fails closed on
  // unparseable URLs and non-http(s) protocols.
  let parsed: URL;
  try {
    parsed = new URL(url);
  } catch {
    throw new Error(
      `Client produced an unparseable URL (${JSON.stringify(url)}); refusing to send credentials.`,
    );
  }
  if (parsed.protocol === "https:" || parsed.protocol === "wss:") return;
  const h = parsed.hostname;
  const isLoopback =
    h === "localhost" ||
    h.endsWith(".localhost") ||
    h === "127.0.0.1" ||
    h === "::1" ||
    h === "[::1]";
  const isInsecureScheme = parsed.protocol === "http:" || parsed.protocol === "ws:";
  const insecureAllowed =
    isInsecureScheme && (isLoopback || allowInsecureHttp);
  if (!insecureAllowed) {
    throw new Error(
      parsed.protocol === "http:"
        ? `Refusing to send credentials over http:// to non-loopback host "${h}". Use https:// in production; set allowInsecureHttp on the client options for LAN/device development.`
        : `Unsupported protocol ${parsed.protocol} for credential-bearing requests.`,
    );
  }
  // allowInsecureHttp permits the HTTP connection itself, but never for
  // credential-bearing requests to non-loopback hosts. Cookies count:
  // even with auth:false, `credentials: "include"` (or `"same-origin"`
  // to a same-origin http target) still sends session cookies.
  if (isInsecureScheme && !isLoopback && (auth || credentials !== "omit")) {
    throw new Error(
      `Refusing to send credentials over http:// to non-loopback host "${h}". Set allowInsecureHttp for the connection, but credentialed requests (auth: true or credentials !== "omit") still require https:// or a loopback host.`,
    );
  }
}

function createRequest(options: YAuthClientOptions) {
  const { baseUrl, credentials = "include" } = options;
  // Bind fetch to its original receiver: calling an unbound
  // globalThis.fetch reference throws "Illegal invocation" in several
  // browser engines.
  const boundFetch =
    options.fetch !== undefined ? options.fetch : globalThis.fetch.bind(globalThis);

  async function request<T>(path: string, opts?: RequestOptions): Promise<T>;
  async function request<T>(
    path: string,
    opts: RequestOptions | undefined,
    rawResponse: true,
  ): Promise<Response>;
  async function request<T>(
    path: string,
    opts: RequestOptions = {},
    rawResponse?: boolean,
  ): Promise<T | Response> {
    const { method = "GET", body, query, auth = false, permissive = false } = opts;
    let url = `${baseUrl}${path}`;
    if (query) {
      const params = new URLSearchParams();
      for (const [key, value] of Object.entries(query)) {
        // Arrays expand to repeated keys (?tag=a&tag=b), the conventional
        // encoding for list-valued parameters.
        for (const v of Array.isArray(value) ? value : [value]) {
          if (v !== undefined && v !== null) {
            params.append(key, String(v));
          }
        }
      }
      const qs = params.toString();
      if (qs) url += `?${qs}`;
    }

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...(options.requestInit?.headers ?? {}),
    };

    // Credentials are only sent over https, to loopback hosts over http,
    // or when the client was explicitly configured with allowInsecureHttp.
    // allowInsecureHttp permits the HTTP connection itself, but never for
    // credential-bearing requests (auth or cookies) to non-loopback hosts.
    assertSecureTransport(url, { allowInsecureHttp: options.allowInsecureHttp === true, auth, credentials });

    // A [permissive] route attaches credentials when available but never
    // fails for want of them; any other [auth] route requires a token.
    if (auth) {
      if (permissive) {
        if (options.getToken) {
          const token = await options.getToken();
          if (token) headers.Authorization = `Bearer ${token}`;
        }
      } else {
        if (!options.getToken) {
          throw new Error(
            `Route declared [auth] but options.getToken was not configured (${method} ${path})`,
          );
        }
        const token = await options.getToken();
        if (!token) {
          throw new Error(
            `options.getToken() returned no token for an [auth] route (${method} ${path})`,
          );
        }
        headers.Authorization = `Bearer ${token}`;
      }
    }

    // Only credentialless calls to routes declaring `[allow_redirects]`
    // follow redirects; anything carrying auth or cookies refuses, since the
    // guard sees only the initial URL and a 3xx could bounce to http://.
    const canFollowRedirects =
      !auth && credentials === "omit" && opts.allowRedirects === true;
    const response = await boundFetch(url, {
      ...options.requestInit,
      ...(auth ? { cache: "no-store" as const } : {}),
      redirect: canFollowRedirects ? "follow" : "error",
      method,
      credentials,
      headers,
      body: body !== undefined ? JSON.stringify(body) : undefined,
    });

    if (!response.ok) {
      const text = await response.text();
      let message: string;
      let errorBody: unknown;
      try {
        const json = JSON.parse(text);
        message = json.error ?? json.message ?? text;
        errorBody = json;
      } catch {
        message = text;
      }
      const error = new YAuthError(message, response.status, errorBody);
      if (options.onError) options.onError(error);
      throw error;
    }

    if (rawResponse) return response;

    const text = await response.text();
    return (text ? JSON.parse(text) : undefined) as T;
  }

  return request;
}

export interface TypedWebSocket<TSend, TReceive> {
  send(event: TSend): void;
  onOpen(handler: () => void): void;
  onMessage(handler: (event: TReceive) => void): void;
  onError(handler: (event: Event) => void): void;
  onClose(handler: (event: CloseEvent) => void): void;
  close(code?: number, reason?: string): void;
  readonly readyState: number;
}

function createTypedWebSocket<TSend, TReceive>(ws: WebSocket): TypedWebSocket<TSend, TReceive> {
  return {
    send(event: TSend) { ws.send(JSON.stringify(event)); },
    onOpen(handler: () => void) { ws.addEventListener("open", handler); },
    onMessage(handler: (event: TReceive) => void) {
      ws.addEventListener("message", (raw: MessageEvent) => {
        handler(JSON.parse(raw.data as string) as TReceive);
      });
    },
    onError(handler: (event: Event) => void) { ws.addEventListener("error", handler); },
    onClose(handler: (event: CloseEvent) => void) { ws.addEventListener("close", handler); },
    close(code?: number, reason?: string) { ws.close(code, reason); },
    get readyState() { return ws.readyState; },
  };
}

// Runtime semantics version — bump when generated helper behavior changes,
// so consumers can detect stale committed artifacts.
export const RUNTIME_VERSION = "0.3.0";

export type YAuthClient = ReturnType<typeof createYAuthClientRoutes> & {
  withOptions(override: Partial<YAuthClientOptions>): YAuthClient;
};

export function createYAuthClient(options: YAuthClientOptions): YAuthClient {
  const request = createRequest(options);

  /** Derived client with the given options merged over this client's. */
  const withOptions = (override: Partial<YAuthClientOptions>): YAuthClient =>
    createYAuthClient({ ...options, ...override });

  const routes = createYAuthClientRoutes(request, options);
  return Object.assign(routes, { withOptions });
}

function createYAuthClientRoutes(request: RequestFn, options: YAuthClientOptions) {
  return {
    getSession: () => request<SessionResponse>("/session", { method: "GET", auth: true, permissive: false, allowRedirects: false }),
    logout: () => request<SuccessResponse>("/logout", { method: "POST", auth: true, permissive: false, allowRedirects: false }),
    updateProfile: (body: UpdateProfileRequest) =>
      request<ProfileResponse>("/me", { method: "PATCH", auth: true, permissive: false, allowRedirects: false, body }),

    "admin": {
      listUsers: (query?: ListUsersQuery) =>
        request<ListUsersResponse>("/admin/users", { method: "GET", auth: true, permissive: false, allowRedirects: false, query }),
      getUser: (id: string) =>
        request<UserResponse>(`/admin/users/${encodeURIComponent(id)}`, { method: "GET", auth: true, permissive: false, allowRedirects: false }),
      deleteUser: (id: string) =>
        request<void>(`/admin/users/${encodeURIComponent(id)}`, { method: "DELETE", auth: true, permissive: false, allowRedirects: false }),
      banUser: (id: string, body: BanRequest) =>
        request<UserResponse>(`/admin/users/${encodeURIComponent(id)}/ban`, { method: "POST", auth: true, permissive: false, allowRedirects: false, body }),
    },

    "emailPassword": {
      register: (body: RegisterRequest) =>
        request<MessageResponse>("/register", { method: "POST", permissive: false, allowRedirects: false, body }),
      login: (body: LoginRequest) =>
        request<LoginResponse>("/login", { method: "POST", permissive: false, allowRedirects: false, body }),
      verify: (body: VerifyEmailRequest) =>
        request<MessageResponse>("/verify-email", { method: "POST", permissive: false, allowRedirects: false, body }),
      changePassword: (body: ChangePasswordRequest) =>
        request<MessageResponse>("/change-password", { method: "POST", auth: true, permissive: false, allowRedirects: false, body }),
    },

    "oauth": {
      authorize: (provider: string, query?: AuthorizeQuery) => {
        let url = `${options.baseUrl}/oauth/${encodeURIComponent(provider)}/authorize`;
        if (query) {
          const params = new URLSearchParams();
          for (const [key, value] of Object.entries(query)) {
            if (value !== undefined && value !== null) params.set(key, String(value));
          }
          const qs = params.toString();
          if (qs) url += `?${qs}`;
        }
        return url;
      },
      callback: (provider: string, body: CallbackBody) =>
        request<AuthResponse>(`/oauth/${encodeURIComponent(provider)}/callback`, { method: "POST", permissive: false, allowRedirects: false, body }),
    },

    "realtime": {
      wsUpgrade: (query?: WsParams): TypedWebSocket<ClientEvent, ServerEvent> => {
        const baseUrl = options.baseUrl.replace(/^http/, (m) => m === "https" ? "wss" : "ws");
        let url = `${baseUrl}/ws`;
        if (query) {
          const params = new URLSearchParams();
          for (const [key, value] of Object.entries(query)) {
            if (value !== undefined && value !== null) params.set(key, String(value));
          }
          const qs = params.toString();
          if (qs) url += `?${qs}`;
        }
        assertSecureTransport(url, { allowInsecureHttp: options.allowInsecureHttp === true, auth: true, credentials: options.credentials ?? "include" });
        const ws = new WebSocket(url);
        return createTypedWebSocket<ClientEvent, ServerEvent>(ws);
      },
    },
  };
}

